stages:
  - stage:build
  - stage:deploy

default:
  image: 'registry.nimbusweb.co/docker/nimbus-node:16.2'

job:build:
  stage: stage:build
  cache:
    key:
      prefix: 'demo-cache'
      files:
        - package.json
        - package-lock.json
    paths:
      - tmp/nx
      - tmp/npm
  artifacts:
    paths:
      - dist
  script:
    - 'node -v && npm -v'
    - 'npm ci --cache=tmp/npm'
    - 'npm run nx run-many -- --all --target=lint'
    - 'npm run nx run-many -- --all --target=test'
    - 'npm run nx run-many -- --all --target=build'
    - 'npm run nx run-many -- --all --target=build-storybook'
    - 'git add -A && git diff --cached'

pages:
  stage: stage:deploy
  script:
    - 'mkdir public'
    - 'echo "Hello" > public/index.html'
  artifacts:
    paths:
      - public
    expire_in: 1 day
