stages:
  - build

default:
  image: 'registry.nimbusweb.co/docker/nimbus-node:16.2'

.build-base:
  stage: build
  script:
    - 'npm run nx run-many -- --all --target=lint'
    - 'npm run nx run-many -- --all --target=test'
    - 'npm run nx run-many -- --all --target=build'
    - 'npm run nx run-many -- --all --target=build-storybook'
    - 'npm run dep-graph -- --file=dist/dep-graph/index.html'
  artifacts:
    paths:
      - dist

build-strict:
  extends: .build-base
  cache:
    key:
      prefix: 'strict-cache'
      files:
        - package-lock.json
    paths:
      - tmp/nx
      - tmp/npm
  before_script:
    - 'node -v && npm -v'
    - 'npm run install-strict'
    - 'npm ls'

build-fast:
  extends: .build-base
  cache:
    key:
      prefix: 'fast-cache'
      files:
        - package-lock.json
    paths:
      - tmp/nx
      - tmp/npm
      - node_modules
  before_script:
    - 'node -v && npm -v'
    - 'npm run install-fast'
    - 'npm ls'
    - 'git add -A && git diff --cached'
