#stages:
#  - stage:build
#  - stage:deploy

pages:
  image: 'registry.nimbusweb.co/docker/nimbus-node:16.2'
  cache:
    key:
      prefix: "full-cache"
      files:
        - ./package.json
        - ./package-lock.json
    paths:
      - ./tmp/nx/
      - ./tmp/npm/
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  script:
    - 'node -v && npm -v'
    - 'npm ci'
    - 'npm run nx run-many -- --all --target=lint'
    - 'npm run nx run-many -- --all --target=test'
    - 'npm run nx run-many -- --all --target=build'
    - 'npm run nx run-many -- --all --target=build-storybook'
    - 'npm run dep-graph -- --file=dist/graph/index.html'
    - 'git add -A && git diff --cached'

#pages:
#  stage: deploy
#  script:
#    - echo 'Nothing to do...'
#  artifacts:
#    paths:
#      - public
#    expire_in: 1 day
#  only:
#    - master
